version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
  pre_build:
    commands:
      - echo "Logging in to ecr..."
      - #$(aws ecr get-login --region ap-south-1)
  build:
    commands:
      - echo Build started on `date`
      - docker build -t sample-app:latest -f Dockerfile .
      - docker tag sample-app:latest ecr-sample-app:latest
  post_build:
    commands:
      - #docker push ecr-sample-app:latest
      - echo Build completed on `date`

